version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: renta-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hyg57aff
      POSTGRES_DB: renta
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - renta-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: renta-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: Hyg57aff
      DB_DATABASE: renta
      JWT_SECRET: 2340dsds932FDSKFSDÆLFKSDLÆFKAØSDFKSDLAÆØFKLSDAKFLÆSDAKSLDÆFKÆSDLKFÆSDLKFSDLÆSDKLØÆFLKDSLÆØFKÆLKZÆLÆsdfkælsdfklædskf
      PORT: 3000
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - renta-network
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run start:dev

networks:
  renta-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
